food/food/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('page', include('page.urls')),
]

food/page/urls.py
from django.urls import path, re_path
from . import views


app_name = 'page'
urlpatterns = [
    path('/', views.IndexView.as_view(), name = 'index'),
    path('/add_food/<int:user_id>', views.AddFood.as_view(), name = 'add_food'),
    path('/foods/<int:user_id>', views.FoodView.as_view(), name = 'foods'),
]

food/page/models.py
from django.db import models
from django.utils import (
    timezone
)

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    

class Food(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food = models.CharField(max_length=50)
    created_at = models.DateTimeField(default=timezone.now)

food/page/forms.py
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    email = forms.EmailField(label='Email')


class FoodForm(forms.Form):
    food = forms.CharField(label='Food', max_length=100)
    user_id = forms.IntegerField(label='user_id')
    

class DelFoodForm(forms.Form):
    food_id = forms.IntegerField(label='food_id')

food/page/views.py
from django.shortcuts import render
from django.http import (
    HttpResponseRedirect
)

from django.urls import (
    reverse,
    reverse_lazy
)

from django.views.generic import (
    FormView
)

from .models import *
from .forms import UserForm, FoodForm, DelFoodForm

# Create your views here.
"""def index(request):
    if request.method == 'POST':
        userForm = UserForm(request.POST)
        
        if userForm.is_valid():
            data = userForm.cleaned_data
            print(data)
            username = data['username']
            email = data['email'].lower()
            
            user = User.objects.filter(email=email)
            
            if len(user) == 0:
                user = User(username=username, email=email)
                user.save()
            else:
                user = user[0]
                user.username = username
                user.save()
            
            user = User.objects.filter(email=email)[0]
            
            return HttpResponseRedirect(reverse('page:foods', args=(user.id,)))
    return render(request, 'page/index.html')
"""


class IndexView(FormView):
    template_name = 'page/index.html'
    form_class = UserForm
    success_url = ''
    
    def form_valid(self, form):
        data = form.cleaned_data
        username = data['username']
        email = data['email'].lower()
        
        user = User.objects.filter(email=email)
        
        if len(user) == 0:
            user = User(username=username, email=email)
            user.save()
        else:
            user = user[0]
            user.username = username
            user.save()
        
        user = User.objects.filter(email=email)[0]
        
        self.success_url = reverse('page:foods', args=(user.id,))
        
        return super().form_valid(form)


"""def foods(request, user_id):
    user = User.objects.filter(id = user_id)[0]
    context = {
        'user': user
    }
    if request.method == 'POST':
        data = dict(request.POST)
        print(data)
        food_id = data['food_id'][0]
        food = Food.objects.filter(id = food_id)[0]
        food.delete()
        message = f"Se elimino {food.food} de las comidas de {user.username}"
        context['message'] = message
    foods = Food.objects.filter(user = user_id)
    context['foods'] = foods
    return render(request, 'page/foods.html', context = context)
"""


class FoodView(FormView):
    template_name = 'page/foods.html'
    form_class = DelFoodForm
    success_url = ''
    message = {
        'message': None,
    }
    
    def form_valid(self, form):
        data = form.cleaned_data
        food_id = data['food_id']
        food = Food.objects.filter(id = food_id)[0]
        food_name = food.food
        user = food.user
        food.delete()
        
        self.success_url = reverse('page:foods', args=(user.id,))
        
        self.message['message'] = f"Se elimino {food_name} de las comidas de {user.username}"
        
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['user_id']
        foods = Food.objects.filter(user = user_id)
        context['user'] = User.objects.filter(id = user_id)[0]
        context['foods'] = foods
        if self.message['message']:
            context['message'] = self.message['message']
        return context


"""def add_food(request, user_id):
    user = User.objects.filter(id = user_id)[0]
    context = {
        'user': user
    }
    if request.method == 'POST':
        foodForm = FoodForm(request.POST)
        if foodForm.is_valid():
            data = foodForm.cleaned_data
            food = data['food']
            user_id = data['user_id']
            food = Food(user = user, food = food)
            food.save()
            context['message'] = f"Se agrego {food.food} a las comidas de {user.username}"
        else:
            context = {
                'title': 'Error'
            }
            return render(request, 'page/add_food.html', context = context)
    return render(request, 'page/add_food.html', context = context)
"""

class AddFood(FormView):
    template_name = 'page/add_food.html'
    form_class = FoodForm
    success_url = ''
    message = {
        'message': None
    }

    def form_valid(self, form):
        data = form.cleaned_data
        food = data['food']
        user_id = data['user_id']
        self.success_url = reverse_lazy('page:add_food', args=(user_id,))
        user = User.objects.filter(id = user_id)[0]
        food = Food(user = user, food = food)
        food.save()
        self.message['message'] = f"Se agrego {food.food} a las comidas de {user.username}"
        
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['user_id']
        context['user'] = User.objects.filter(id = user_id)[0]
        if self.message['message']:
            context['message'] = self.message['message']
        return context

food/page/templates/page/add_food.html
{% extends 'page/base.html' %}
{% load static %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'page/css/alerts.css' %}">
{% endblock styles %}


{% block title %}
    {% if title %}
        {{ block.super }}
    {% else %}
        Agregar Comida
    {% endif %}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-4">
        <h1 class="col text-center">
            Agregar comida para {{ user.username }}
        </h1>
    </div>
    {% if message %}
    <div class="row d-flex justify-content-center" id="message">
        <div class="alert alert-success text-center" role="alert">
            {{ message }}
        </div>
    </div>
    {% endif %}
    <div class="row container d-flex justify-content-center">
        <form action="{% url 'page:add_food' user.id %}" method="post">
            {% csrf_token %}
            <input type="text" name="user_id" id="user_id" value="{{ user.id }}" hidden>
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <input type="text" class="form-control col" id="food" name="food" required placeholder="Nueva Comida" required>
                </div>
            </div>
            <div class="row d-flex justify-content-evenly mt-3">
                <button type="submit" class="btn btn-success col-4">Agregar</button>
                <a href="{% url 'page:foods' user.id %}" class="btn btn-primary col-4">Finalizar</a>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

food/page/templates/page/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% endblock styles %}
    <title>
        {% block title %}
            {% if title %}
                {{ title }}
            {% endif %}
        {% endblock title %}
    </title>
</head>
<body {% block body_data %}class="bg-dark text-light" {% endblock body_data %}>
    {% include 'page/navbar.html' %}
    {% block content %}{% endblock content %}
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% endblock scripts %}
</body>
</html>

food/page/templates/page/foods.html
{% extends 'page/base.html' %}
{% load static %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'page/css/list.css' %}">
<link rel="stylesheet" href="{% static 'page/css/alerts.css' %}">
{% endblock styles %}

{% block title %}
Comida de {{ user.username }}
{% endblock title %}

{% block content %}
<div class="container justify-content-center">
    <div class="row mt-4">
        <h1 class="col text-center">Comida de {{ user.username }}</h1>
    </div>
    {% if message %}
    <div class="row d-flex justify-content-center" id="message">
        <div class="alert alert-danger text-center" role="alert">
            {{ message }}
        </div>
    </div>
    {% endif %}

    <ul class="row list-group food-list">
        {% for food in foods %}
            <li class="list-group-item d-flex justify-content-around text-light list-item">
                <p class="col-4 h4">
                    {{ food.food }}
                </p>
                <p class="col-4">
                    {{ food.created_at }}
                </p>
                <form action="{% url 'page:foods' user.id %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="food_id" value="{{ food.id }}" hidden>
                    <input type="submit" hidden id="submit_{{ food.id }}">
                    </input>
                    <label for="submit_{{ food.id }}" class="col-2 delete-food">
                        <span>🗑️</span>
                    </label>
                </form>
            </li>
        {% endfor %}
    </ul>
    
    <div class="row d-flex justify-content-center mt-4">
        <a href="{% url 'page:add_food' user.id%}" class="btn btn-success text-dark col-5">
            Agregar comida
        </a>
    </div>
</div>

{% endblock content %}

food/page/templates/page/index.html
{% extends 'page/base.html' %}

{% block title %}
    {% if title %}
        {{ block.super }}
    {% else %}
        Ingresar
    {% endif %}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-4">
        <h1 class="col text-center">Ingresar</h1>
    </div>
    <div class="row container d-flex justify-content-center">
        <form action="{% url 'page:index' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label"></label>
                <input type="text" class="form-control" id="username" name="username" required placeholder="Name">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label"></label>
                <input type="email" class="form-control" id="email" name="email" required placeholder="Email">
            </div>
            <button type="submit" class="btn btn-primary col-10 offset-1 mt-3">Ir</button>
        </form>
    </div>
</div>

{% endblock content %}

food/page/templates/page/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'page:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            {% if user.email %}
                <div class="nav-item">
                    <p class="nav-link disabled">Viendo a {{ user.email }}</p>
                </div>
            {% endif %}
        </div>
    </div>
</nav>